name: Second Worklfow
on:
  workflow_dispatch
jobs:
  job-1:
    name: CLI
    runs-on: ubuntu latest
    steps:
      - run:
          echo "step 1"
          echo "step 2"
          
  job-2:
    name: Cowsays
    runs-on: ubuntu latsest
    steps:
      - name: Ship it
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'ship ship ship!'
          color: 'red'


    
