name: Second Worklfow
on:
  workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    name: CLI
    steps:
      - run: |
          echo "step 1"
          echo "step 2"
          
  job-2:
    runs-on: ubuntu-latest
    name: Cowsays
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'red'


    
